#!/bin/bash
# USAGE: start|status
#
case "$1" in
start)
echo "Starting Theodo Lights."
nohup /opt/theodo-lights/theodo-lights.py &
;;
status)
# Check to see if the process is running
ps aux|grep -i theodo-lights
;;

*)
echo “Theodo Lights Web Portal Service”
echo $”Usage: $0 {start|status}”
exit 1
esac
exit 0
